name: Semgrep scan

on:
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch: {}
  schedule:
    - cron: "10 22 * * 6"

jobs:
  call-workflow-semgrep:
    permissions:
      security-events: write
    uses: gsoft-inc/wl-reusable-workflows/.github/workflows/reusable-semgrep-workflow.yml@main
